# Generated by Django 2.0.5 on 2018-05-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_albummodel_photomodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photomodel',
            name='pdate',
        ),
        migrations.RemoveField(
            model_name='photomodel',
            name='phit',
        ),
        migrations.RemoveField(
            model_name='photomodel',
            name='psubject',
        ),
        migrations.RemoveField(
            model_name='photomodel',
            name='purl',
        ),
        migrations.AddField(
            model_name='photomodel',
            name='pimg',
            field=models.ImageField(default='temp/', upload_to='<django.db.models.fields.related.ForeignKey>/'),
        ),
    ]
