# Generated by Django 2.0.5 on 2018-05-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20180527_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='photomodel',
            name='dir_name',
            field=models.CharField(default='temp', max_length=50),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='pimg',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
