# Generated by Django 2.0.5 on 2018-05-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20180527_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photomodel',
            name='dir_name',
        ),
        migrations.AddField(
            model_name='photomodel',
            name='ptitle',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='pimg',
            field=models.ImageField(upload_to='photo/'),
        ),
    ]
