# Generated by Django 2.0.5 on 2018-05-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20180527_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photomodel',
            old_name='ptitle',
            new_name='psubject',
        ),
        migrations.AddField(
            model_name='photomodel',
            name='pdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
