# Generated by Django 2.0.5 on 2018-05-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20180528_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photomodel',
            name='pimg',
            field=models.CharField(max_length=100),
        ),
    ]
