# Generated by Django 2.0.5 on 2018-05-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20180528_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photomodel',
            name='pimg',
            field=models.ImageField(upload_to='photo/'),
        ),
    ]
